# Auto-generated AWS resource classes from Infracost

from .docdb_cluster_instance import *
from .dx_connection import *
from .s3_standard_storage_class import *
from .lambda_provisioned_concurrency_config import *
from .ebs_snapshot_copy import *
from .s3_bucket import *
from .redshift_cluster import *
from .fsx_windows_file_system import *
from .route53_resolver_endpoint import *
from .vpn_connection import *
from .s3_bucket_inventory import *
from .ec2_client_vpn_endpoint import *
from .route53_health_check import *
from .waf_web_acl import *
from .backup_vault import *
from .kinesisanalyticsv2_application import *
from .cloudformation_stack import *
from .cloudfront_distribution import *
from .db_instance import *
from .remediater import *
from .api_gateway_stage import *
from .codebuild_project import *
from .elasticache_cluster import *
from .instance import *
from .cloudtrail import *
from .elastic_beanstalk_environment import *
from .launch_configuration import *
from .data_transfer import *
from .neptune_cluster_instance import *
from .cloudwatch_log_group import *
from .rds_cluster_instance import *
from .acm_certificate import *
from .ec2_host import *
from .s3_intelligent_tiering_storage_class import *
from .global_accelerator_endpoint_group import *
from .glue_catalog_database import *
from .docdb_cluster import *
from .kms_external_key import *
from .sqs_queue import *
from .s3_bucket_analytics_configuration import *
from .ecs_service import *
from .grafana_workspace import *
from .s3_glacier_flexible_retrieval_storage_class import *
from .kinesisanalytics_application import *
from .ec2_client_vpn_network_association import *
from .directory_service_directory import *
from .global_accelerator import *
from .dynamodb_table import *
from .neptune_cluster import *
from .util import *
from .eks_cluster import *
from .ebs_snapshot import *
from .lightsail_instance import *
from .dms_replication_instance import *
from .eks_node_group import *
from .glue_crawler import *
from .route53_record import *
from .launch_template import *
from .elb import *
from .networkfirewall_firewall import *
from .ec2_transit_gateway_vpc_attachment import *
from .autoscaling_group import *
from .ssm_activation import *
from .ebs_volume import *
from .sfn_state_machine import *
from .sns_topic import *
from .rds_cluster import *
from .ecr_repository import *
from .cloudformation_stack_set import *
from .config_configuration_recorder import *
from .s3_one_zone_infrequent_access_storage_class import *
from .cloudwatch_metric_alarm import *
from .kms_key import *
from .kinesisanalyticsv2_application_snapshot import *
from .ec2_traffic_mirror_session import *
from .apigatewayv2_api import *
from .s3_standard_infrequent_access_storage_class import *
from .fsx_openzfs_file_system import *
from .nat_gateway import *
from .dx_gateway_association import *
from .app_autoscaling_target import *
from .neptune_cluster_snapshot import *
from .ec2_transit_gateway_peering_attachment import *
from .wafv2_web_acl import *
from .s3_glacier_deep_archive_storage_class import *
from .msk_cluster import *
from .mwaa_environment import *
from .elasticache_replication_group import *
from .cloudwatch_event_bus import *
from .sns_topic_subscription import *
from .config_config_rule import *
from .eks_fargate_profile import *
from .mq_broker import *
from .api_gateway_rest_api import *
from .lambda_function import *
from .kinesis_firehose_delivery_stream import *
from .cloudwatch_dashboard import *
from .search_domain import *
from .secretsmanager_secret import *
from .ssm_parameter import *
from .efs_file_system import *
from .glue_job import *
from .lb import *
from .acmpca_certificate_authority import *
from .vpc_endpoint import *
from .kinesis_stream import *
from .route53_zone import *
from .cloudhsm_v2_hsm import *
from .transfer_server import *
from .cloudfront_function import *
from .docdb_cluster_snapshot import *
from .eip import *
