AWSTemplateFormatVersion: '2010-09-09'
Description: 'Pricing Calculator MCP Service - ECS Fargate service with ALB integration'

Parameters:
  VpcId:
    Type: String
    Default: vpc-0123456789abcdef0
    Description: VPC ID for the service
  
  PublicSubnetIds:
    Type: CommaDelimitedList
    Default: "subnet-0123456789abcdef0,subnet-0123456789abcdef1"
    Description: Public subnet IDs for ECS tasks
  
  ALBSecurityGroupId:
    Type: String
    Default: sg-0123456789abcdef0
    Description: Security group ID of the existing MCP ALB
  
  ALBListenerArn:
    Type: String
    Default: arn:aws:elasticloadbalancing:us-east-1:500330120558:listener/app/internal-mcp-internal-alb/1234567890123456/1234567890123456
    Description: ARN of the existing ALB listener

Resources:
  # Security Group for Pricing Calculator Service
  PricingCalcSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for pricing calculator MCP service
      VpcId: !Ref VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          SourceSecurityGroupId: !Ref ALBSecurityGroupId
          Description: Allow inbound from ALB on port 8080
      SecurityGroupEgress:
        - IpProtocol: -1
          CidrIp: 0.0.0.0/0
          Description: Allow all outbound traffic
      Tags:
        - Key: Name
          Value: pricingcalc-mcp-sg

  # ECS Cluster (reuse existing or create new)
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: mcp-cluster
      CapacityProviders:
        - FARGATE
      DefaultCapacityProviderStrategy:
        - CapacityProvider: FARGATE
          Weight: 1

  # Task Definition
  PricingCalcTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: pricingcalc-mcp
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      Cpu: 256
      Memory: 512
      ExecutionRoleArn: !Ref ECSExecutionRole
      TaskRoleArn: !Ref ECSTaskRole
      ContainerDefinitions:
        - Name: pricingcalc-mcp
          Image: !Sub "${AWS::AccountId}.dkr.ecr.${AWS::Region}.amazonaws.com/pricingcalc-mcp:latest"
          PortMappings:
            - ContainerPort: 8080
              Protocol: tcp
          HealthCheck:
            Command:
              - CMD-SHELL
              - "curl -f http://localhost:8080/health || exit 1"
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 60
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: !Ref CloudWatchLogGroup
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: pricingcalc-mcp
          Environment:
            - Name: AWS_DEFAULT_REGION
              Value: !Ref AWS::Region

  # CloudWatch Log Group
  CloudWatchLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/pricingcalc-mcp
      RetentionInDays: 7

  # ECS Execution Role
  ECSExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
      Policies:
        - PolicyName: ECRAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                Resource: '*'

  # ECS Task Role
  ECSTaskRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: S3Access
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                Resource: '*'
        - PolicyName: PricingAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - pricing:GetProducts
                  - pricing:DescribeServices
                Resource: '*'

  # Target Group
  PricingCalcTargetGroup:
    Type: AWS::ElasticLoadBalancingV2::TargetGroup
    Properties:
      Name: pricingcalc-mcp-tg
      Port: 8080
      Protocol: HTTP
      VpcId: !Ref VpcId
      TargetType: ip
      HealthCheckPath: /health
      HealthCheckProtocol: HTTP
      HealthCheckIntervalSeconds: 30
      HealthCheckTimeoutSeconds: 5
      HealthyThresholdCount: 2
      UnhealthyThresholdCount: 3

  # ALB Listener Rule
  ALBListenerRule:
    Type: AWS::ElasticLoadBalancingV2::ListenerRule
    Properties:
      ListenerArn: !Ref ALBListenerArn
      Priority: 100
      Conditions:
        - Field: path-pattern
          Values:
            - /pricingcalc*
      Actions:
        - Type: forward
          TargetGroupArn: !Ref PricingCalcTargetGroup

  # ECS Service
  PricingCalcService:
    Type: AWS::ECS::Service
    DependsOn: ALBListenerRule
    Properties:
      ServiceName: pricingcalc-mcp
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref PricingCalcTaskDefinition
      LaunchType: FARGATE
      DesiredCount: 1
      NetworkConfiguration:
        AwsvpcConfiguration:
          SecurityGroups:
            - !Ref PricingCalcSecurityGroup
          Subnets: !Ref PublicSubnetIds
          AssignPublicIp: ENABLED
      LoadBalancers:
        - ContainerName: pricingcalc-mcp
          ContainerPort: 8080
          TargetGroupArn: !Ref PricingCalcTargetGroup
      HealthCheckGracePeriodSeconds: 120

Outputs:
  ServiceName:
    Description: Name of the ECS service
    Value: !Ref PricingCalcService
    Export:
      Name: !Sub "${AWS::StackName}-ServiceName"
  
  TargetGroupArn:
    Description: ARN of the target group
    Value: !Ref PricingCalcTargetGroup
    Export:
      Name: !Sub "${AWS::StackName}-TargetGroupArn"
  
  ServiceEndpoint:
    Description: Endpoint for the pricing calculator service
    Value: !Sub "http://internal-mcp-internal-alb-2059913293.us-east-1.elb.amazonaws.com/pricingcalc"
    Export:
      Name: !Sub "${AWS::StackName}-ServiceEndpoint"
